// Generate sample PDFs for all property types
// Run: node scripts/generate-samples.mjs

import { writeFileSync } from 'fs'
import { execSync } from 'child_process'

// We need to use the Next.js build output, so let's hit the API directly
// But since the API needs to run in Next.js context, we'll create a standalone script

const samples = [
  {
    name: 'HDB-Standard',
    tier: 'standard',
    formData: {
      propertyType: 'hdb',
      propertyAddress: 'Blk 123 Ang Mo Kio Avenue 3',
      unitNumber: '#08-456',
      postalCode: '560123',
      landlordName: 'TAN AH KOW',
      landlordNric: 'S1234567A',
      landlordAddress: '456 Bukit Timah Road, #12-01, Singapore 259756',
      tenantName: 'JOHN SMITH',
      tenantNric: 'G1234567N',
      tenantEmail: 'john.smith@example.com',
      additionalTenants: [],
      commencementDate: '2026-04-01',
      expiryDate: '2028-03-31',
      monthlyRent: 2800,
      securityDeposit: 5600,
      hdbApprovalObtained: true,
      handoverCondition: 'furnished',
      leaseRenewalOption: true,
      diplomaticClause: false,
      customClauses: ['AIRCON_TENANT', 'NO_SMOKING', 'MINOR_REPAIRS'],
      utilityCap: '',
      petDescription: '',
      freeTextClause: '',
      roomType: 'common',
      roomDescription: '',
      utilitiesIncluded: false,
      utilitiesSplitMethod: 'equal',
      utilitiesFixedAmount: '',
      wifiIncluded: false,
      sharedFacilities: [],
      houseRules: '',
      paymentBank: 'DBS',
      paymentAccountName: 'TAN AH KOW',
      paymentAccountNo: '012-345678-9',
      rentPaymentDay: 1,
      minorRepairThreshold: 150,
      diplomaticMinMonths: 12,
      diplomaticNoticeMonths: 2,
      renewalTermMonths: 12,
      purchaseNoticeMonths: 2,
      inventoryItems: [
        { name: 'Refrigerator (Samsung)', condition: 'good' },
        { name: 'Washing Machine (LG)', condition: 'good' },
        { name: 'Aircon x3 (Daikin)', condition: 'good' },
        { name: 'Queen Bed + Mattress (Master)', condition: 'fair' },
        { name: 'Dining Table + 4 Chairs', condition: 'good' },
      ],
      skipParties: false,
      skipTerms: false,
      skipProperty: false,
    }
  },
  {
    name: 'Private-Custom',
    tier: 'custom',
    formData: {
      propertyType: 'private',
      propertyAddress: '8 Sentosa Cove',
      unitNumber: '#15-02',
      postalCode: '098888',
      landlordName: 'LIM MEI LING',
      landlordNric: 'S9876543B',
      landlordAddress: '100 Orchard Road, #20-05, Singapore 238840',
      tenantName: 'DAVID MUELLER',
      tenantNric: 'F8765432P',
      tenantEmail: 'david.mueller@company.com',
      additionalTenants: [
        { name: 'SARAH MUELLER', nricPassport: 'E1234567X' }
      ],
      commencementDate: '2026-05-01',
      expiryDate: '2028-04-30',
      monthlyRent: 8500,
      securityDeposit: 17000,
      hdbApprovalObtained: false,
      handoverCondition: 'furnished',
      leaseRenewalOption: true,
      diplomaticClause: true,
      customClauses: ['AIRCON_LANDLORD', 'NO_PETS', 'MINOR_REPAIRS', 'LANDLORD_ACCESS', 'ORIGINAL_CONDITION', 'VIEWING_CLAUSE'],
      utilityCap: '',
      petDescription: '',
      freeTextClause: 'The Landlord shall provide weekly pool maintenance at the Landlord\'s expense throughout the tenancy period.',
      roomType: 'common',
      roomDescription: '',
      utilitiesIncluded: false,
      utilitiesSplitMethod: 'equal',
      utilitiesFixedAmount: '',
      wifiIncluded: false,
      sharedFacilities: [],
      houseRules: '',
      paymentBank: 'OCBC',
      paymentAccountName: 'LIM MEI LING',
      paymentAccountNo: '501-234567-001',
      rentPaymentDay: 1,
      minorRepairThreshold: 200,
      diplomaticMinMonths: 12,
      diplomaticNoticeMonths: 2,
      renewalTermMonths: 24,
      purchaseNoticeMonths: 2,
      inventoryItems: [
        { name: 'Smart TV 65" (Sony)', condition: 'good' },
        { name: 'Refrigerator (Bosch)', condition: 'good' },
        { name: 'Washer/Dryer (Miele)', condition: 'good' },
        { name: 'Aircon x4 (Mitsubishi)', condition: 'good' },
        { name: 'King Bed + Mattress (Master)', condition: 'good' },
        { name: 'Sofa Set (3+2 seater)', condition: 'good' },
        { name: 'Wine Chiller (Vintec)', condition: 'fair' },
      ],
      skipParties: false,
      skipTerms: false,
      skipProperty: false,
    }
  },
  {
    name: 'Room-Rental',
    tier: 'standard',
    formData: {
      propertyType: 'room',
      propertyAddress: 'Blk 456 Tampines Street 42',
      unitNumber: '#12-789',
      postalCode: '520456',
      landlordName: 'WONG WEI MING',
      landlordNric: 'S5678901C',
      landlordAddress: 'Blk 456 Tampines Street 42, #12-789, Singapore 520456',
      tenantName: 'MARIA SANTOS',
      tenantNric: 'G9876543M',
      tenantEmail: 'maria.santos@email.com',
      additionalTenants: [],
      commencementDate: '2026-03-15',
      expiryDate: '2027-03-14',
      monthlyRent: 1100,
      securityDeposit: 1100,
      hdbApprovalObtained: true,
      handoverCondition: 'furnished',
      leaseRenewalOption: false,
      diplomaticClause: false,
      customClauses: ['NO_SMOKING', 'NO_SUBLET'],
      utilityCap: '',
      petDescription: '',
      freeTextClause: '',
      roomType: 'common',
      roomDescription: 'Common room with built-in wardrobe, window facing east, ceiling fan and aircon.',
      utilitiesIncluded: false,
      utilitiesSplitMethod: 'equal',
      utilitiesFixedAmount: '',
      wifiIncluded: true,
      sharedFacilities: ['Kitchen', 'Living Room', 'Bathroom (shared)', 'Laundry Area'],
      houseRules: '1. No overnight guests without prior approval from Landlord.\n2. Quiet hours: 10PM to 8AM.\n3. Keep shared areas clean after use.\n4. No cooking of strong-smelling food without proper ventilation.\n5. Shoes to be left at the door.',
      paymentBank: 'UOB',
      paymentAccountName: 'WONG WEI MING',
      paymentAccountNo: '301-567890-1',
      rentPaymentDay: 15,
      minorRepairThreshold: 100,
      diplomaticMinMonths: 12,
      diplomaticNoticeMonths: 2,
      renewalTermMonths: 12,
      purchaseNoticeMonths: 2,
      inventoryItems: [
        { name: 'Single Bed + Mattress', condition: 'good' },
        { name: 'Built-in Wardrobe', condition: 'good' },
        { name: 'Study Desk + Chair', condition: 'fair' },
        { name: 'Ceiling Fan', condition: 'good' },
        { name: 'Aircon (Daikin)', condition: 'good' },
      ],
      skipParties: false,
      skipTerms: false,
      skipProperty: false,
    }
  }
]

// Output as JSON for the API to consume
console.log(JSON.stringify(samples, null, 2))
